// <auto-generated />
using System;
using DAR.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAR.Infrastructure.DiagramMigrations
{
    [DbContext(typeof(DiagramContext))]
    [Migration("20191102225603_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("DAR.API.Model.Attribute", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<string>("CLB");

                    b.Property<string>("Class");

                    b.Property<string>("Comm");

                    b.Property<string>("Description");

                    b.Property<int?>("HMLId");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("HMLId");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("DAR.API.Model.Dependency", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Destination");

                    b.Property<int?>("HMLId");

                    b.Property<string>("Source");

                    b.HasKey("Id");

                    b.HasIndex("HMLId");

                    b.ToTable("ARDs");
                });

            modelBuilder.Entity("DAR.API.Model.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ordered");

                    b.HasKey("Id");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("DAR.API.Model.HML", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Version");

                    b.HasKey("Id");

                    b.ToTable("HMLs");
                });

            modelBuilder.Entity("DAR.API.Model.Property", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("HMLId");

                    b.HasKey("Id");

                    b.HasIndex("HMLId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("DAR.API.Model.Reference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Destination");

                    b.Property<string>("PropertyId");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("References");
                });

            modelBuilder.Entity("DAR.API.Model.Transformation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Destination");

                    b.Property<int?>("HMLId");

                    b.Property<string>("Source");

                    b.HasKey("Id");

                    b.HasIndex("HMLId");

                    b.ToTable("TPHs");
                });

            modelBuilder.Entity("DAR.API.Model.Type", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Base");

                    b.Property<string>("Description");

                    b.Property<int?>("DomainId");

                    b.Property<int?>("HMLId");

                    b.Property<string>("Length");

                    b.Property<string>("Name");

                    b.Property<string>("Scale");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("HMLId");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("DAR.API.Model.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DomainId");

                    b.Property<string>("From");

                    b.Property<string>("Is");

                    b.Property<string>("Num");

                    b.Property<string>("To");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("DAR.API.Model.Attribute", b =>
                {
                    b.HasOne("DAR.API.Model.HML")
                        .WithMany("Attributes")
                        .HasForeignKey("HMLId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAR.API.Model.Dependency", b =>
                {
                    b.HasOne("DAR.API.Model.HML")
                        .WithMany("ARD")
                        .HasForeignKey("HMLId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAR.API.Model.Property", b =>
                {
                    b.HasOne("DAR.API.Model.HML")
                        .WithMany("Properties")
                        .HasForeignKey("HMLId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAR.API.Model.Reference", b =>
                {
                    b.HasOne("DAR.API.Model.Property")
                        .WithMany("References")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAR.API.Model.Transformation", b =>
                {
                    b.HasOne("DAR.API.Model.HML")
                        .WithMany("TPH")
                        .HasForeignKey("HMLId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAR.API.Model.Type", b =>
                {
                    b.HasOne("DAR.API.Model.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId");

                    b.HasOne("DAR.API.Model.HML")
                        .WithMany("Types")
                        .HasForeignKey("HMLId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAR.API.Model.Value", b =>
                {
                    b.HasOne("DAR.API.Model.Domain")
                        .WithMany("Values")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
